spring:
  application:
    name: address-lookup

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/concertdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: utf8
          useUnicode: true
        # Force Hibernate to use exact table names as specified in @Table annotations
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        # Use physical naming strategy to respect @Table annotations
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        hbm2ddl:
          auto: none
    database-platform: org.hibernate.dialect.MySQLDialect